name: Init environment

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: 'yarn'

    - name: Install dependencies
      run: yarn --frozen-lockfile
      shell: bash
